# Generated by Django 6.0 on 2026-01-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailingattempt",
            name="subscriber",
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="server_mail_response",
            field=models.TextField(verbose_name="Ответ почтового сервера"),
        ),
    ]
