# Generated by Django 6.0 on 2026-01-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_remove_mailingattempt_subscriber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingmodel",
            name="beginning_sending",
            field=models.DateTimeField(
                help_text="Укажите время в формате ГГГГ.ММ.ДД ЧЧ:ММ:СС",
                verbose_name="Начало рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="mailingmodel",
            name="end_sending",
            field=models.DateTimeField(
                help_text="Укажите время в формате ГГГГ.ММ.ДД ЧЧ:ММ:СС",
                verbose_name="Конец рассылки",
            ),
        ),
    ]
